#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # CORE (MANDATORY) DO NOT CHANGE ###########################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'coder'
        intport: '8080'
        extport: '8080'
        dev_extport: '5000'
        dev_intport: '5000'
        image: 'codercom/code-server'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # LABELS #### KEEPS BOTTOM CLEAN ###########################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.coder.port: '{{intport}}'
          traefik.coder.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}'
          traefik.coder.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.coder.frontend.headers.SSLRedirect: 'true'
          traefik.coder.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.coder.frontend.headers.STSPreload: 'true'
          traefik.coder.frontend.headers.STSSeconds: '315360000'
          traefik.coder.frontend.headers.browserXSSFilter: 'true'
          traefik.coder.frontend.headers.contentTypeNosniff: 'true'
          traefik.coder.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.coder.frontend.headers.forceSTSHeader: 'true'
          traefik.coder_dev.port: '{{dev_intport}}'
          traefik.coder_dev.frontend.rule: 'Host:{{pgrole}}_dev.{{domain.stdout}}{{tldset}}'
          traefik.coder_dev.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.coder_dev.frontend.headers.SSLRedirect: 'true'
          traefik.coder_dev.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.coder_dev.frontend.headers.STSPreload: 'true'
          traefik.coder_dev.frontend.headers.STSSeconds: '315360000'
          traefik.coder_dev.frontend.headers.browserXSSFilter: 'true'
          traefik.coder_dev.frontend.headers.contentTypeNosniff: 'true'
          traefik.coder_dev.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.coder_dev.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '{{path.stdout}}:{{path.stdout}}'
          - '/mnt:/mnt'
          - '/opt/appdata/{{pgrole}}/projects:/home/coder/project'
          - '/opt/appdata/{{pgrole}}/config:/home/coder/.local/share/code-server'
          
    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'

    # MAIN SCRIPT ##############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
          - '{{ports.stdout}}{{dev_extport}}:{{dev_intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
